# Generated by Django 5.2.8 on 2025-11-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_envio', models.CharField(max_length=300)),
                ('estado_envio', models.CharField(choices=[('pending', 'Pendiente'), ('in_transit', 'En tránsito'), ('delivered', 'Entregado'), ('failed', 'Fallo entrega')], default='pending', max_length=20)),
                ('transportador', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('costo_envio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='pedidos.pedido')),
            ],
        ),
    ]
